server:
  port: 8080
spring:
  datasource:
    name: test
    url: jdbc:mysql://192.168.40.134:3306/project_manage_system
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  cache:
    ehcache:
      config: classpath:ehcache.xml
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.pms.entity,com.hfy.entity
logging:
  level:
    tk: debug
    com:
      hfy:
        mapper: debug
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql